server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        # Route đến user-service
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**, /api/auth/**

        # Route đến product-service
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/api/products/**
      # Các bộ lọc mặc định
      default-filters:
        - RemoveRequestHeader=Cookie

      # Thêm tính năng CORS nếu frontend chạy ở localhost:3000 (Next.js)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"

# custom:
#   route-roles:
#     - path: /api/admin/**
#       required-roles: ROLE_ADMIN
#     - path: /api/products/**
#       required-roles: ROLE_USER