server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # ========== USER SERVICE ==========
            - id: user-service-auth
              uri: http://user-service:8080
              predicates:
                - Path=/api/auth/**

            - id: user-service-users
              uri: http://user-service:8080
              predicates:
                - Path=/api/users/**

            # ========== PRODUCT SERVICE ==========
            - id: product-service
              uri: http://product-service:8080
              predicates:
                - Path=/api/products/**

          # Bộ lọc mặc định
          default-filters:
            - RemoveRequestHeader=Cookie

          # CORS cho frontend React
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:3000"
                allowedMethods: "*"
                allowedHeaders: "*"
